name: UI Docs

on:
  workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            storybook/package-lock.json

      - name: Install Modules
        run: npm ci

      - name: Install Storybook Modules
        run: npm run install-storybook

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install Expo
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          packager: npm

      - name: Run Doc
        run: npm run doc

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'doc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
