name: Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Run Unit Tests
        run: npm run test-ci

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Run Lints
        run: npm run lint-all
